
services:
  postgres_primary:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
    depends_on: []
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8888:8888
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8888

networks:
  default:
    driver: bridge
    name: webapp

volumes:
  postgres_data:
    driver: local