
services:
  postgres_primary:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
    depends_on: []
  postgres_replica1:
    image: postgres:15-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=password
    depends_on:
      - postgres_primary
  postgres_replica2:
    image: postgres:15-alpine
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=password
    depends_on:
      - postgres_primary
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8888:8888
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8888
  postgres_setup:
    image: postgres:15-alpine
    user: root
    volumes:
        - ./tmp/postgres/data:/var/lib/postgresql/data
        - ./tmp/postgres/config:/etc/postgresql
    entrypoint: [ "bash", "-c", "chmod 750 -R /var/lib/postgresql/data && chmod 750 -R /etc/postgresql"] 
    depends_on:
        - postgres_primary
    init: true

networks:
  default:
    driver: bridge
    name: webapp